# Generated by Django 3.0.8 on 2020-09-21 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centroAdocao', '0002_testitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='centroAdocao',
        ),
        migrations.DeleteModel(
            name='DadosCentroAdocao',
        ),
        migrations.DeleteModel(
            name='testModel',
        ),
    ]
