# Generated by Django 3.0.8 on 2020-09-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroAdocao', '0003_auto_20200921_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosCentroAdocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
