# Generated by Django 3.0.8 on 2020-09-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroAdocao', '0004_dadoscentroadocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscentroadocao',
            name='email',
            field=models.EmailField(default='invalido', max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='dadoscentroadocao',
            name='gato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dadoscentroadocao',
            name='nome',
            field=models.CharField(default='invalido', max_length=40),
        ),
        migrations.AddField(
            model_name='dadoscentroadocao',
            name='quantidade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
