# Generated by Django 3.0.8 on 2020-09-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroAdocao', '0005_auto_20200921_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscentroadocao',
            name='img',
            field=models.ImageField(default='imagesData/erro.jpg', upload_to='imagesData/'),
        ),
    ]
